linters:
  # Disable all linters.
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - errcheck
    - godot
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
