apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
  - image: "ghcr.io/canonical/identity-platform-admin-ui"
    sync:
      infer:
      - "cmd/main.go"
      - "go.mod"
      - "go.sum"
    docker:
    platforms: ["linux/amd64"]        
  local:
    push: false

test:
  - image: "ghcr.io/canonical/identity-platform-admin-ui"
    structureTests:
      - './structure-tests.yaml'


manifests:
  rawYaml:
    - "deployments/kubectl/*"

deploy:
  kubectl:
  helm:
    releases:
      - name: postgresql
        remoteChart: oci://registry-1.docker.io/bitnamicharts/postgresql
        valuesFiles: ["deployments/helm/postgresql/values.yaml"]
      - name: kratos
        remoteChart: kratos
        repo: https://k8s.ory.sh/helm/charts
        valuesFiles: ["deployments/helm/kratos/values.yaml"]
        wait: false
      - name: hydra
        remoteChart: hydra
        repo: https://k8s.ory.sh/helm/charts
        valuesFiles: ["deployments/helm/hydra/values.yaml"]
        wait: false
      - name: oathkeeper
        remoteChart: oathkeeper
        repo: https://k8s.ory.sh/helm/charts
        setValues:
          demo: "true"
        wait: false

portForward:
- resourceType: service
  resourceName: identity-platform-admin-ui
  namespace: default
  port: 80
  localPort: 8000
