demo: false
maester:
  enabled: false
service:
  proxy:
    enabled: false
  metrics:
    enabled: false
oathkeeper:
  managedAccessRules: true
  accessRules: |
    [
      {
        "id": "admin-rule-1",
        "upstream": {
          "url": "https://httpbin.org/anything"
        },
        "match": {
          "url": "http://<[^/]+>/authenticator/noop/authorizer/allow/mutator/noop",
          "methods": ["GET", "POST", "PUT", "DELETE", "PATCH"]
        },
        "authenticators": [
          {
            "handler": "noop"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ]
      },
      {
        "id": "admin-rule-2",
        "upstream": {
          "url": "https://httpbin.org/anything"
        },
        "match": {
          "url": "http://<[^/]+>/authenticator/anonymous/authorizer/allow/mutator/header",
          "methods": ["GET", "POST", "PUT", "DELETE", "PATCH"]
        },
        "authenticators": [
          {
            "handler": "anonymous"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "header"
          }
        ]
      },
      {
        "id": "admin-rule-3",
        "upstream": {
          "url": "https://httpbin.org/anything"
        },
        "match": {
          "url": "http://<[^/]+>/authenticator/anonymous/authorizer/allow/mutator/id_token",
          "methods": ["GET", "POST", "PUT", "DELETE", "PATCH"]
        },
        "authenticators": [
          {
            "handler": "anonymous"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "id_token"
          }
        ]
      }
    ]
  config:
    access_rules:
      repositories:
        - file:///etc/rules/access-rules.json
    authenticators:
      anonymous:
        enabled: true
      noop:
        enabled: true
      unauthorized:
        enabled: true
    authorizers:
      allow:
        enabled: true
      deny:
        enabled: true
    mutators:
      cookie:
        enabled: true
        config:
          cookies:
            user: "<nil>"
      header:
        enabled: true
        config:
          headers:
            X-User: "<nil>"
      noop:
        enabled: true
    serve:
      api:
        cors:
          enabled: true
