---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-platform-admin-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-platform-admin-ui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: identity-platform-admin-ui
      annotations:
        prometheus.io/path: /api/v0/metrics
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      volumes:
        - name: certificates
          persistentVolumeClaim:
            claimName: certificates-volume-claim
      initContainers:
        - name: init-ca-certificates
          image: ubuntu:22.04
          command: ["sh", "-c", "apt update && apt install -y ca-certificates"]
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: certificates
      containers:
        - image: identity-platform-admin-ui
          name: identity-platform-admin-ui
          command: ["/usr/bin/identity-platform-admin-ui", "serve"]
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: certificates
          envFrom:
            - configMapRef:
                name: identity-platform-admin-ui
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: "/api/v0/status"
              port: 8000
            initialDelaySeconds: 1
            failureThreshold: 10
            timeoutSeconds: 5
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: "/api/v0/status"
              port: 8000
            initialDelaySeconds: 1
            failureThreshold: 10
            timeoutSeconds: 5
            periodSeconds: 30
      imagePullSecrets:
        - name: regcred-github
