---
apiVersion: batch/v1
kind: Job
metadata:
  name: admin-ui-openfga-setup
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: job
          image: identity-platform-admin-ui
          command: ["/usr/bin/identity-platform-admin-ui", "create-fga-model", "--fga-api-url", "http://openfga.default.svc.cluster.local:8080", "--fga-api-token", "42", "--store-k8s-configmap-resource", "default/identity-platform-admin-ui"]

      restartPolicy: Never
