---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: certificates-volume
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/certificates-k8s
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certificates-volume-claim
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi