name: container scan
run-name: Scanning container ${{ inputs.image }} to ghcr.io/canonical/identity-platform-admin-ui

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
        description: "image to scan"
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - name: Scan image with Trivy
      uses: aquasecurity/trivy-action@2736533278103862a861f4a35ebac3e97854d956 # master
      with:
        image-ref: ${{ inputs.image }}
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload scan results to GitHub
      uses: github/codeql-action/upload-sarif@5595ccaf912efad79be6eef63a5619ff05969be3 # v4
      with:
        sarif_file: 'trivy-results.sarif'