name: container scan
run-name: Scanning container ${{ inputs.image }} to ghcr.io/canonical/identity-platform-admin-ui

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
        description: "image to scan"
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - name: Scan image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.image }}
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload scan results to GitHub
      uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4
      with:
        sarif_file: 'trivy-results.sarif'